name: Deploy Prod

run-name: Deploying ${{ github.event.inputs.releaseTag }} to prod

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Tag of version to be promoted to prod'
        required: true

env:
  TF_VERSION: 0.14.7
  TG_VERSION: 0.37.1
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: prod
  TARGET_ENV: prod
  FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.releaseTag }}

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" "${FONTAWESOME_PACKAGE_TOKEN}"
          yarn install --silent --frozen-lockfile

      ### Build if no cache exists ###
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            **/dist
          key: ${{ github.sha }}-dist
      - name: Run Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        env:
          GITHUB_SHA_SHORT: ${{ github.sha }}
        run: |
          sed 's@localConfigEndpoint@'true'@g' src/env.js.template | sed 's@gitHubHash@'"$GITHUB_SHA_SHORT"'@g' > src/env.js
          yarn build
          ./node_modules/.bin/ngsw-config dist/parks-reso-public/ ./ngsw-config.json /dayuse

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN_TO_USE }}
          role-duration-seconds: 900
          role-session-name: parks-reso-public-prod-gh-action
          role-skip-session-tagging: true

      - name: Get public variables
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/parks-reso-public/s3-bucket = S3_BUCKET, /parks-reso-public/origin-id = ORIGIN_ID'

      - name: Get API variables
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/parks-reso-api/origin-domain = API_GATEWAY_ORIGIN_DOMAIN, /parks-reso-api/origin-id = API_GATEWAY_ORIGIN_ID, /parks-reso-api/gateway-path-pattern = API_GATEWAY_PATH_PATTERN'

      - name: Get shared variables
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/parks-reso-shared/s3-bucket-assets = S3_BUCKET_ASSETS, /parks-reso-shared/origin-id-assets = ORIGIN_ID_ASSETS'

      ### Upload dist to S3 ###
      - name: Deploy to Prod S3
        env:
          s3_bucket: '${{ env.S3_BUCKET }}-${{ env.TARGET_ENV }}'
          dir_name: ${{ github.event.inputs.releaseTag }}
        run: |
          aws s3 sync dist/parks-reso-public s3://$s3_bucket/$dir_name/dayuse

      ### Run Terragrunt ###
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          app_version: ${{ github.event.inputs.releaseTag }}
          aws_region: ${{ secrets.AWS_REGION }}
          s3_bucket: ${{ env.S3_BUCKET }}
          s3_bucket_assets: ${{ env.S3_BUCKET_ASSETS }}
          origin_id: ${{ env.ORIGIN_ID }}
          api_gateway_origin_domain: ${{ env.API_GATEWAY_ORIGIN_DOMAIN }}
          api_gateway_origin_id: ${{ env.API_GATEWAY_ORIGIN_ID }}
          api_gateway_path_pattern: ${{ env.API_GATEWAY_PATH_PATTERN }}
          origin_id_assets: ${{ env.ORIGIN_ID_ASSETS }}
          auth_user: ${{ secrets.BASIC_AUTH_USER }}
          auth_pass: ${{ secrets.BASIC_AUTH_PASS }}
          ssl_cert_arn: ${{ secrets.PARKS_SSL_CERT_ARN }}
        run: terragrunt apply -auto-approve --terragrunt-non-interactive -var aws_region=${{ secrets.AWS_REGION }} -var target_aws_account_id=${{ vars.ACCOUNT_ID }} -var target_env=prod

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"