name: Pull Request

on: [pull_request]

jobs:
  pr:
    name: pr
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, and test
        run: |
          npm install
          npm run tests-ci
          npm run lint
        env:
          CI: true
